[package]
name = "mcdmrs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rayon = "1.8.1"

[dev-dependencies]
criterion = "0.5.1"
is_close = "0.1.3"

[profile.release]
lto = true
codegen-units = 1
strip = true

[[example]]
name = "prom_usual"

[[bench]]
name = "bench_main"
harness = false
