[package]
name = "promrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.8.1"

[profile.release]
# debug = true
lto = true
codegen-units = 1
strip = true

[dev-dependencies]
is_close = "0.1.3"
