[package]
name = "mcdmrs"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.37.0", optional = true }
clap = { version = "4.5.1", features = ["derive"], optional = true }
rand = "0.8.5"
rayon = "1.8.1"

[features]
default = ["io", "cli"]
io = ["dep:polars"]
cli = ["dep:clap"]

[dev-dependencies]
polars = "0.37.0"
criterion = "0.5.1"
is_close = "0.1.3"


[profile.release]
lto = true
codegen-units = 1
strip = true

[[example]]
name = "prom_usual"

[[bench]]
name = "bench_main"
harness = false
