[package]
name = "py-mcdmrs"
version = "0.1.0"
edition = "2021"

[lib]
name = "mcdmrs"
crate-type = ["cdylib"]

[dependencies]
mcdmrs-prom = { workspace = true }
pyo3 = { version = "0.20", features = ["extension-module"] }
numpy = "0.20"
