pub mod math;
mod multicriterion_flow;
pub use multicriterion_flow::multicriterion_flow;
pub mod interop;
mod pref_functions;
mod promethee;
pub use promethee::Prom;
pub mod types;
pub use types::Criteria;
pub mod unicriterion_flow;
pub mod utils;
