pub mod matrix;
mod multicriterion_flow;
pub use multicriterion_flow::multicriterion_flow;
mod prom;
pub use prom::{Criteria, Prom};
pub mod interop;
mod pref_functions;
pub mod types;
pub mod unicriterion_flow;
pub mod utils;
