name: Lint & Test Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linters
        run: |
          rustup component add rustfmt --toolchain nightly
          rustup component add clippy --toolchain nightly
          cargo fmt --all -- --check
          cargo clippy --no-deps

  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run coverage
        run: |
          make install-rust-coverage
          make coverage-ci
      - name: upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "./mcdmrs.lcov"
