name: Lint & Test Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linters
        run: |
          cargo fmt --all -- --check
          cargo clippy --no-deps

  test_coverage_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run coverage
        run: |
          make install-rust-coverage
          make coverage-ci
      - name: upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "./mcdmrs.lcov"

  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build Python
        run: |
          pip install ruff
      - name: Lint
        run: |
          ruff check .
          ruff format . --diff

  test_coverage_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build Python
        run: |
          pip install -e crates/py-mcdmrs[test]
      - name: Test Coverage
        run: |
          make coverage-python
      - name: upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
